import { getMessages } from 'next-intl/server';
import "./globals.css";
import { ThemeContextProvider } from '@/contexts/ThemeContext';
import ScrollToTopButton from "@/components/Effects/ScrollToTopButton";
import FloatingButton from "@/components/Effects/FloatingButton";
import { NextIntlClientProvider } from 'next-intl';
import Head from 'next/head';
import 'aos/dist/aos.css';
import localFont from 'next/font/local'
export const generateMetadata = async ({ params: { locale } }: { params: { locale: string } }) => ({
  title: `KhanhLinh_Profile - ${locale}`,
  description: `Generated by create next app in ${locale}`,
});

const myFont = localFont({
  src: './Montserrat-VariableFont_wght.ttf',
  display: 'swap',
})

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages({ locale });

  return (
    <html lang={locale} className={myFont.className}>
      <Head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
        <meta name="description" content={`Khanh_Linh_Proile ${locale}`} />
      </Head>
      <body className="bg-white dark:bg-[#0d2438] text-gray-700 dark:text-gray-100 ">
        <NextIntlClientProvider messages={messages}>
          <ThemeContextProvider>
            {children}
            <ScrollToTopButton />
            <FloatingButton />
          </ThemeContextProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
